### ISSUE TITLE
Any thoughts on adding a ENV VAR or Flag to allow eviction of Daemon Sets

### ISSUE THREAD

**Issue by CAR6807** [deitch/aws-asg-roller#1]
https://github.com/deitch/aws-asg-roller/blob/5ee76753a68ada176c49d3bb993b23a765fdcc88/kubernetes.go#L70
Any thoughts on adding a ENV VAR or Flag to allow eviction of Daemon Sets?
I would like to cluster autoscaler to re-claim nodes but DS are still present on nodes

**Comment by deitch** [comment]
Either way, no harm in the option.

**Comment by CAR6807** [comment]
No, I think you cleared it up. CA does reclaim the nodes even if DS are present. The very nature of the DS, it cannot be cordoned off or deleted from the node, even with Kube drain command. Regardless I appreciate you taking the time to look at this, I will close the issue.

**Comment by deitch** [comment]
No problem. I created the option anyways - if Kubernetes makes it an option, there is a reason for it - but I have a hard time seeing who would use it and when.
