### ISSUE TITLE
Verbose logs are printing pointer memory address instead of value

### ISSUE THREAD

**Issue by TwinProduction** [deitch/aws-asg-roller#40]
Based on my documentation as well as tests I ran from my end, #39 should've been correct, but it's printing the pointer's memory address now.

That being said, it did fix the issue with panic, but now the verbose logs are partially unhelpful.

I'm working on a fix right now, but I wanted to create an issue until the PR was merged in case others are also experiencing this issue.

**Comment by deitch** [comment]
Thanks for staying on top of it @TwinProduction
