### ISSUE TITLE
Option to not force drain a node from kubernetes

### ISSUE THREAD

**Issue by gregsidelinger** [deitch/aws-asg-roller#52]
https://github.com/deitch/aws-asg-roller/blob/0b31468befe7598286c7cb82e97cb121d6329af9/kubernetes.go#L72-L77

Would it be possible to create an option to not force delete standalone pods?  We have a bunch of short term running pods that are not managed by a deployment or job that should be given a chance to finish running.  Since there is no backing deployment I can not use a Pod Disruption Budget to instruct kube to not delete them so setting the force=false and trying again later is the only option I can think of.

**Comment by deitch** [comment]
Certainly. The hardest part about this usually is the user interface, with [everything in env vars](https://github.com/deitch/aws-asg-roller#configuration), but we don't have too many, so it shouldn't be too bad. Maybe `ROLLER_PREVENT_DRAIN` or similar?

Go for a PR.
